### ISSUE TITLE
Fetching half of the lyrics

### ISSUE THREAD

**Issue by 00davidr** [Smile4ever/VLC-Lyrics-Finder#11]
The plugin fetches the lyrics but doesn't show it completely , and when I maximize the lyrics finder's window it's the same! either lyric isn't completely fetched or it doesn't show it fully.
![1](https://user-images.githubusercontent.com/11700683/31437137-1e5aa4c8-ae91-11e7-818f-b4c7a4465ea0.JPG)
![2](https://user-images.githubusercontent.com/11700683/31437138-1f4bdd16-ae91-11e7-9898-43a887a6ce09.JPG)

 

Thx bro great job

**Comment by Smile4ever** [comment]
This is a problem with metrolyrics. I will release a fix when I have time, I hope this week or soon after that.

**Comment by mi12078** [comment]
Hey, I as well noticed this issue recently so I attemped a fix located here: #12.
Only checked for a couple of songs, the one included from @00davidr.
![screenshot_20171011_225433](https://user-images.githubusercontent.com/11778692/31466385-457554cc-aed7-11e7-93e4-565656d25de0.png)

**Comment by Smile4ever** [comment]
Having the pull request speeds up the process! I will release an installation package for Windows with the fixed code soon.

**Comment by Smile4ever** [comment]
Fixed in VLC Lyrics Finder 0.3.6.
https://github.com/Smile4ever/VLC-Lyrics-Finder/commit/d941cd0f9a29b042401b4cb4680f008c0e0dadb0
