### ISSUE TITLE
Extension open once only

### ISSUE THREAD

**Issue by haytham-med** [Smile4ever/VLC-Lyrics-Finder#17]
Hi, the extension opens only once you start vlc, if you close lyrics dialog, won't open anymore from View.

**Comment by htfy96** [comment]
Same here. Logs:

```
qt debug: activating or triggering extension 'Lyrics Finder'
lua debug: Reactivating extension Lyrics Finder
lua debug: Lua 5.3
lua debug: [Lyrics Finder] Activating 
lua warning: Error while running script /home/vic/.local/share/vlc/lua/extensions/lyricsfinder.lua, function activate(): /home/vic/.local/share/vlc/lua/extensions/lyricsfinder.lua:304: attempt to index a nil value (global 'translation')
lua error: Could not activate extension!
lua debug: Deactivating 'Lyrics Finder'
```

**Comment by Smile4ever** [comment]
This might be related to a new VLC release. I should track the issue down to the root cause.

**Comment by fotofrank** [comment]
> Hi, the extension opens only once you start vlc, if you close lyrics dialog, won't open anymore from View.

This issue is solved for me, when I start VLC as Administrator.
