### ISSUE TITLE
Overlapping layout of lyrics search results.

### ISSUE THREAD

**Issue by arolle** [Smile4ever/VLC-Lyrics-Finder#4]
On MacOSX, a lyrics search yields the following window, whose size can not be altered. The lyrics are displayed on top of the search bar. The lyrics for `Buenos hermanos` by `Ibrahim Ferrer` were searched (and retrieved).

Thanks your work on the add-on. Let me know how I can help to fix this bug.

![screen shot 2015-10-18 at 10 22 42](https://cloud.githubusercontent.com/assets/1167984/10563251/07313e7c-7583-11e5-857e-0778d00f4c1d.png)

**Comment by Smile4ever** [comment]
Hi. This seems like a OS X specific issue. Let's investigate.

Which version of VLC do you use?

Which version of OS X do you use?

What's the output of Tools -> Messages? Steps to test:
* Open video/music file
* Open Tools -> Messages and change the level to debug
* Open Lyrics Finder
* Copy the text / save it to a file and drop it here.
