### ISSUE TITLE
Which plugin/extension can display lyrics of songs in Linux?

### ISSUE THREAD

**Issue by Sunsetra** [Smile4ever/VLC-Lyrics-Finder#8]
Excuse me. I'm interested in your extension, but I can't find a usable plugin/extension that can display lyrics of songs in Linux.
If possible, could you tell me which plugin/extension can display lyrics of songs in Linux?

**Comment by Smile4ever** [comment]
Hi I use Linux myself. You can use VLC Lyrics Finder on Linux too, just copy "lyricsfinder.lua" and the folder "locale" into
Linux user path: /home/$USER/.local/share/vlc/lua/extensions
or
Linux system path: /usr/share/vlc/lua/extensions

**Comment by xingxuanma** [comment]
Yeah, I got it. It's useful.
But some lyrics of my songs have no search result. Is it possible to link local lyrics to songs? Or making the lyrics automatically scroll when the songs are playing?

**Comment by Smile4ever** [comment]
If you have songs without search results please let me know and I'll try to fix those. I was once thinking of making an offline lyrics cache but that's not a reality yet.

Autoscrolling is probably not possible because VLC does not expose a method to scroll down (correct me if I'm wrong).

**Comment by Smile4ever** [comment]
Some ideas that are probably feasible:
* Implement reading of SRT files to prevent network requests
* Implement a lyrics cache (TXT format files)

**Comment by lawabb** [comment]
Works on Ubuntu 18.04  - lua file saved to /usr/lib/x86_64-linux-gnu/vlc/lua/extensions
What would also be good would be to check mp3 ID 'lyrics' tag (first). Another option is to run a local server for lyrics like mpd remote  has the option for (for cover art).

**Comment by CmdrGF** [comment]
I'm using linux Mint 20-Cinnamon and the latest lyricfinder/lua in the correct vlc user directory but when I select View-LyricsFinder, often nothing happens. This is cured each time by closing and restarting vlc but when lyricsfinder starts it correctly gets the track name and album but just hangs on "loading..."
This happens with any track. I'm running VLC 3.0.9.2.
Any ideas? Gregory
