### ISSUE TITLE
FR: Save found lyrics into a local text file

### ISSUE THREAD

**Issue by PeterCodar** [Smile4ever/VLC-Lyrics-Finder#9]
Nice extension, thank you!

Could you please add a functionality to save the found lyrics into a local text file?
(This file can be imported in the track by any other already existing program and I think this would be less effort then saving the lyrics back in the track itself.)
Please save the file with the known informations like
Aerosmith - Eat the rich.txt

An option to save the file automatically without pressing a button would be perfect!

**Comment by 71m383nd3r** [comment]
I'm looking for this feature too. 
Is there a possibility to see it in near future?

**Comment by Smile4ever** [comment]
This has been implemented in VLC Lyrics Finder 0.3.7.

A few command line windows will open on Windows in order to save the lyrics text. If you have a better idea to write text to a file from within a VLC extension, you're welcome to submit an improvement.
